common:
    lid_topic:  "/velodyne_points"
    imu_topic:  "/handsfree/imu"
    time_sync_en: false         # ONLY turn on when external time synchronization is really not possible

preprocess:
    lidar_type: 2                # 1 for Livox serials LiDAR, 2 for Velodyne LiDAR, 3 for ouster LiDAR,
    scan_line: 32
    scan_rate: 10                # only need to be set for velodyne, unit: Hz,
    blind: 2
    point_filter_num: 4

mapping:
    down_sample_size: 0.4
    max_iteration: 3
    voxel_size: 1.6
    max_layer: 3                # 4 layer, 0, 1, 2, 3
    layer_point_size: [ 5, 5, 5, 5, 5 ]
    plannar_threshold: 0.01
    max_points_size: 1000      # #todo
    max_cov_points_size: 1000  # #todo

    fov_degree:    360
    det_range:     100.0
    extrinsic_est_en:  false      # true: enable the online estimation of IMU-LiDAR extrinsic,
    extrinsic_T: [ 0.27255, -0.00053, 0.17954 ]
    extrinsic_R: [ 1, 0, 0,
                   0, 1, 0,
                   0, 0, 1 ]
    extrinsic_q_en: false

noise_model:
    ranging_cov: 0.04
    angle_cov: 0.1
    acc_cov: 3.7686306102624571e-02
    gyr_cov: 2.3417543020438883e-03
    b_acc_cov: 1.1416642385952368e-03
    b_gyr_cov: 1.4428407712885209e-05

cov_incremental:
    num_update_thread: 4

publish:
    pub_voxel_map: false
    publish_max_voxel_layer: 1         # only publish 0,1,2 layer's plane
    path_en:  true
    scan_publish_en:  true       # false: close all the point cloud output
    dense_publish_en: true       # false: low down the points number in a global-frame point clouds scan.
    scan_bodyframe_pub_en: true  # true: output the point cloud scans in IMU-body-frame

pcd_save:
    pcd_save_en: false
    interval: -1                 # how many LiDAR frames saved in each pcd file;
    # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.


# prism or RTK in IMU frame
ground_truth:
    extrinsic_T: [ 0.16, 0.0, 0.84 ]   ## GNSS in IMU frame
#    extrinsic_T: [ 0.27255, -0.00053, 0.17954]    ## LiDAR in IMU frame
    extrinsic_R: [ 1, 0, 0,
                   0, 1, 0,
                   0, 0, 1 ]
